apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-blue
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: blue
  template:
    metadata:
      labels:
        app: flask-app
        version: blue
    spec:
      containers:
        - name: flask
          image: docker.io/library/devops-flask:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5007
          readinessProbe:
            httpGet:
              path: /health
              port: 5007
            initialDelaySeconds: 5
            periodSeconds: 10

