apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: devops
spec:
  type: NodePort
  selector:
    app: flask-app
    version: blue
  ports:
    - port: 80
      targetPort: 5007
      nodePort: 30080

